// <auto-generated />
namespace CHY_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inheritancechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inheritancechange));
        
        string IMigrationMetadata.Id
        {
            get { return "201611220320087_inheritancechange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
